### ISSUE TITLE
Suggestion for TCP transport

### ISSUE THREAD

**Issue by cachedout** [tonybaloney/readysalted#1]
Hey Tony!

This all looks really cool. You've got some stuff outlined here that I've wanted to do for a long time.

Regarding the difficulty of getting libzmq to go on things like micropython, I think the way to go here might be to support the TCP transport first and then come back to ZMQ. We're hoping to have it as a first-class citizen and have been testing transport fallback masters for a while now. Let me know if you'd like help. You're on to something here. :]

**Comment by s0undt3ch** [comment]
You beat me to it! TCP FTW!!!!

**Comment by tonybaloney** [comment]
What about MQTT transport? By their nature, the IoT devices are low latency on unreliable connections so TCP wouldn't be ideal. You'd need to code a lot of retry, fail back logic into the master. Would the events still get queued? 

Wrt to micro python, I made some notes on this https://medium.com/@anthonypjshaw/intel-edison-v-s-esp8266-64ec5f3d4467#.rwqlefhmu

**Comment by cachedout** [comment]
I've looked (briefly) at MQTT. Definitely worth exploring more.

**Comment by tonybaloney** [comment]
see https://github.com/tonybaloney/readysalted#option-4---write-a-mqtt-transport-module-for-saltstack 
and also Option 1. But i think transport module is the way to go. ZMQ is really sweet for servers but for little tiny devices it we need something designed a little differently.
